name: Check Tests Didnt Change
on:
  push:
    branches:
      - master
    paths:
      - '**/__tests__/**'

jobs:
  checkTests:
    name: check Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
          token: ${{ secrets.PAT_TOKEN }}
      - run: |
          git config user.name 'Mike Franco'
          git config user.email 'mfranco_98@yahoo.com'
          git pull origin master
          git reset --hard HEAD^
          git add -A
          git commit -m "Se cambiaron los tests, regresando al commit anterior"
          git push origin master --force
  slackNotification:
    name: Notify Slack
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Notify Slack
      uses: drilonrecica/action-slack-notify@0.0.3
      env:
        # https://slack.com/apps/A0F7XDUAZ-incoming-webhooks para obtener el secret de abajo
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_CHANNEL: general
        SLACK_COLOR: '#F20606'
        SLACK_MESSAGE: 'Te andamos checando :eyes:, no hagas cambios en los tests :inexpresivo:'
        SLACK_USERNAME: Mike's bot
        SLACK_TITLE: Tests has changed
        SLACK_ICON: https://avatars3.githubusercontent.com/u/39423201?s=48&v=4



