name: Notify Slack Demo
on:
  push:
    branches:
      - master

jobs:
  slackNotification:
    name: Notify Slack
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Notify Slack
      uses: drilonrecica/action-slack-notify@0.0.3
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK}}
        SLACK_CHANNEL: productdevelopment
        SLACK_COLOR: '#000066'
        SLACK_MESSAGE: 'Prueba GitHubAction :robot_face:, ignorar el mensaje :smile:'
        SLACK_USERNAME: "Mike's bot :robot_face:"
        SLACK_TITLE: Post Title
        SLACK_ICON: https://avatars3.githubusercontent.com/u/39423201?s=48&v=4