name: Notify Slack Demo
on:
  push:
    branches:
      - develop

jobs:
  checkTestsDidntChange:
    name: checkTests
    runs-on: ubunt-latest
    steps:
  #Solo hará este job si el job(checar que los tests no se hayan modificado) job.status == 'failure'
  slackNotification:
    name: Notify Slack
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Notify Slack
      uses: drilonrecica/action-slack-notify@0.0.3
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_CHANNEL: general
        SLACK_COLOR: '#000066'
        SLACK_MESSAGE: 'Te andamos checando :eyes:, no borres los tests :inexpresive:'
        SLACK_USERNAME: Mike's bot
        SLACK_TITLE: Post Title
        SLACK_ICON: https://avatars3.githubusercontent.com/u/39423201?s=48&v=4